### PR TITLE
Mac spinlock 304

### LINKED ISSUE #304: no pthread_spinlock_t on mac
New Issue for sst-macro
-----------------------

1 - Detailed description of problem or enhancement
Builds using --enable-spinlock fail on OSX since some functionality lives under different names: 
```
In file included from ../../../sst-macro/sstmac/common/runtime.cc:53:
In file included from ../../../sst-macro/sstmac/backends/common/parallel_runtime.h:51:
../../../sst-macro/sstmac/common/thread_lock.h:101:3: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
  pthread_spinlock_t lock_;
  ^~~~~~~~~~~~~~~~~~
  pthread_rwlock_t
/usr/include/sys/_pthread/_pthread_rwlock_t.h:30:35: note: 'pthread_rwlock_t' declared here
typedef __darwin_pthread_rwlock_t pthread_rwlock_t;
                                  ^
1 error generated.
```

2 - Describe how to reproduce
Try to configure with --enable-spinlock on OSX 

3 - What Operating system(s) and versions 
OS X

4 - What version of external libraries (Boost, MPI)
Neither 

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
sst-macro -> b14225b51c09c7e6ea3ad04ddbc98f7a2deda342

This might already be a known issue, but I didn't find it by searching.

### PR DESCRIPTION
**Pull request by calewis**
Fixes #304

### CODE REVIEW

**Comment by calewis** [comment]
Should have done pr for devel not master.

**Comment by allevin** [comment]
@calewis You don't have to close the PR if it is targeted towards the wrong branch.  In the upper left of the PR page, you can click the `edit` button and it will let you change the target branch.

**Comment by calewis** [comment]
Well, I already resubmitted it a new one to devel. Should I just stop that one and reopen this one or let it go?

**Comment by allevin** [comment]
@calewis Just let it go.  Just wanted you to know for the future...

**Pull request closed without merging**
